// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package services

import (
	"github.com/jtomasevic/go-with-graphql-demo/src/services/7seas"
	"github.com/jtomasevic/go-with-graphql-demo/src/services/7seas/data_store/data_source"
)

// Injectors from wire.go:

// InilizeServices. wire is compile-time dependency injection library for Golang.
// First we link interface to it's implementation, and then provide factory method.
//
// Example:--------- interface------------------ implementation-----------
// wire.Bind(new(datasource.DataSource), new(*datasource.DataSourceService)),
// --- factory method.
// datasource.NewDataSource,
//
// Finally we how we bind return value. More about wire: https://github.com/google/wire
func InilizeServices() *Services {
	dataSourceService := datasource.NewDataSource()
	piratesRepo := seas.NewDataStore(dataSourceService)
	sevenSeasService := seas.NewService(piratesRepo)
	services := &Services{
		SevenSeasService: sevenSeasService,
	}
	return services
}
