// Code generated by github.com/vektah/dataloaden, DO NOT EDIT.

package dataloaders

import (
	"sync"
	"time"

	"github.com/google/uuid"
	seas "github.com/jtomasevic/go-with-graphql-demo/src/services/7seas"
)

// CrewLoaderConfig captures the config to create a new CrewLoader
type CrewLoaderConfig struct {
	// Fetch is a method that provides the data for the loader
	Fetch func(keys []uuid.UUID) ([]seas.Crew, []error)

	// Wait is how long wait before sending a batch
	Wait time.Duration

	// MaxBatch will limit the maximum number of keys to send in one batch, 0 = not limit
	MaxBatch int
}

// NewCrewLoader creates a new CrewLoader given a fetch, wait, and maxBatch
func NewCrewLoader(config CrewLoaderConfig) *CrewLoader {
	return &CrewLoader{
		fetch:    config.Fetch,
		wait:     config.Wait,
		maxBatch: config.MaxBatch,
	}
}

// CrewLoader batches and caches requests
type CrewLoader struct {
	// this method provides the data for the loader
	fetch func(keys []uuid.UUID) ([]seas.Crew, []error)

	// how long to done before sending a batch
	wait time.Duration

	// this will limit the maximum number of keys to send in one batch, 0 = no limit
	maxBatch int

	// INTERNAL

	// lazily created cache
	cache map[uuid.UUID]seas.Crew

	// the current batch. keys will continue to be collected until timeout is hit,
	// then everything will be sent to the fetch method and out to the listeners
	batch *crewLoaderBatch

	// mutex to prevent races
	mu sync.Mutex
}

type crewLoaderBatch struct {
	keys    []uuid.UUID
	data    []seas.Crew
	error   []error
	closing bool
	done    chan struct{}
}

// Load a seas.Crew by key, batching and caching will be applied automatically
func (l *CrewLoader) Load(key uuid.UUID) (seas.Crew, error) {
	return l.LoadThunk(key)()
}

// LoadThunk returns a function that when called will block waiting for a seas.Crew.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *CrewLoader) LoadThunk(key uuid.UUID) func() (seas.Crew, error) {
	l.mu.Lock()
	if it, ok := l.cache[key]; ok {
		l.mu.Unlock()
		return func() (seas.Crew, error) {
			return it, nil
		}
	}
	if l.batch == nil {
		l.batch = &crewLoaderBatch{done: make(chan struct{})}
	}
	batch := l.batch
	pos := batch.keyIndex(l, key)
	l.mu.Unlock()

	return func() (seas.Crew, error) {
		<-batch.done

		var data seas.Crew
		if pos < len(batch.data) {
			data = batch.data[pos]
		}

		var err error
		// its convenient to be able to return a single error for everything
		if len(batch.error) == 1 {
			err = batch.error[0]
		} else if batch.error != nil {
			err = batch.error[pos]
		}

		if err == nil {
			l.mu.Lock()
			l.unsafeSet(key, data)
			l.mu.Unlock()
		}

		return data, err
	}
}

// LoadAll fetches many keys at once. It will be broken into appropriate sized
// sub batches depending on how the loader is configured
func (l *CrewLoader) LoadAll(keys []uuid.UUID) ([]seas.Crew, []error) {
	results := make([]func() (seas.Crew, error), len(keys))

	for i, key := range keys {
		results[i] = l.LoadThunk(key)
	}

	crews := make([]seas.Crew, len(keys))
	errors := make([]error, len(keys))
	for i, thunk := range results {
		crews[i], errors[i] = thunk()
	}
	return crews, errors
}

// LoadAllThunk returns a function that when called will block waiting for a Crews.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *CrewLoader) LoadAllThunk(keys []uuid.UUID) func() ([]seas.Crew, []error) {
	results := make([]func() (seas.Crew, error), len(keys))
	for i, key := range keys {
		results[i] = l.LoadThunk(key)
	}
	return func() ([]seas.Crew, []error) {
		crews := make([]seas.Crew, len(keys))
		errors := make([]error, len(keys))
		for i, thunk := range results {
			crews[i], errors[i] = thunk()
		}
		return crews, errors
	}
}

// Prime the cache with the provided key and value. If the key already exists, no change is made
// and false is returned.
// (To forcefully prime the cache, clear the key first with loader.clear(key).prime(key, value).)
func (l *CrewLoader) Prime(key uuid.UUID, value seas.Crew) bool {
	l.mu.Lock()
	var found bool
	if _, found = l.cache[key]; !found {
		l.unsafeSet(key, value)
	}
	l.mu.Unlock()
	return !found
}

// Clear the value at key from the cache, if it exists
func (l *CrewLoader) Clear(key uuid.UUID) {
	l.mu.Lock()
	delete(l.cache, key)
	l.mu.Unlock()
}

func (l *CrewLoader) unsafeSet(key uuid.UUID, value seas.Crew) {
	if l.cache == nil {
		l.cache = map[uuid.UUID]seas.Crew{}
	}
	l.cache[key] = value
}

// keyIndex will return the location of the key in the batch, if its not found
// it will add the key to the batch
func (b *crewLoaderBatch) keyIndex(l *CrewLoader, key uuid.UUID) int {
	for i, existingKey := range b.keys {
		if key == existingKey {
			return i
		}
	}

	pos := len(b.keys)
	b.keys = append(b.keys, key)
	if pos == 0 {
		go b.startTimer(l)
	}

	if l.maxBatch != 0 && pos >= l.maxBatch-1 {
		if !b.closing {
			b.closing = true
			l.batch = nil
			go b.end(l)
		}
	}

	return pos
}

func (b *crewLoaderBatch) startTimer(l *CrewLoader) {
	time.Sleep(l.wait)
	l.mu.Lock()

	// we must have hit a batch limit and are already finalizing this batch
	if b.closing {
		l.mu.Unlock()
		return
	}

	l.batch = nil
	l.mu.Unlock()

	b.end(l)
}

func (b *crewLoaderBatch) end(l *CrewLoader) {
	b.data, b.error = l.fetch(b.keys)
	close(b.done)
}
